// <auto-generated />

using System;
using Library.Book.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Library.Book.Api.Migrations
{
    [DbContext(typeof(BookDbContext))]
    internal class BookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Library.Book.Service.Data.Entities.EBook", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnName("ID")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy"
                                   , SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("AuthorId")
                    .HasColumnName("AUTHOR_ID");

                b.Property<DateTime>("Created")
                    .HasColumnName("CREATED")
                    .HasColumnType("datetime2");

                b.Property<string>("CreatedBy")
                    .HasColumnName("CREATED_BY");

                b.Property<string>("LibraryId")
                    .HasColumnName("LIBRARY_ID");

                b.Property<string>("Name")
                    .HasColumnName("NAME");

                b.Property<int>("No")
                    .HasColumnName("NO");

                b.Property<DateTime>("PublishDate")
                    .HasColumnName("PUBLISH_DATE");

                b.Property<int>("PublisherId")
                    .HasColumnName("PUBLISHER_ID");

                b.Property<int>("ShelfId")
                    .HasColumnName("SHELF_NUMBER");

                b.Property<int>("SkinType")
                    .HasColumnName("COVER_STATUS");

                b.Property<string>("Tag")
                    .HasColumnName("GENRE");

                b.Property<DateTime>("Updated")
                    .HasColumnName("UPDATED")
                    .HasColumnType("datetime2");

                b.Property<string>("UpdatedBy")
                    .HasColumnName("UPDATED_BY");

                b.Property<int>("UserId")
                    .HasColumnName("USER_ID");

                b.HasKey("Id");

                b.ToTable("BOOKS");
            });
#pragma warning restore 612, 618
        }
    }
}